### ISSUE TITLE
Does not change the text color

### ISSUE THREAD

**Issue by MarcoLopezPE** [jakeres/jeeeyul-eclipse-themes#2]
I have imported the .epf but the color of the sample text does not change.

**Comment by jakeres** [comment]
hi

you need to use jeeeyul theme; import the epf file there and in eclipse preferences -> appearance ->Jeeeyul's The,es change the theme to Jeeeyul

kind regards

**Comment by MarcoLopezPE** [comment]
lo he importado tal cual, pero el color de fuente sigue igual.
![ctabfolder_2017-12-18_21-08-09](https://user-images.githubusercontent.com/12569642/34137237-c87448ca-e437-11e7-8768-a7d8f3fb2c38.png)

**Comment by jakeres** [comment]
jeeeyul changes only the buttons/menu colors/appearance; the image showed for this task is from an old eclipse version. to change the font size/family please try this 
https://stackoverflow.com/questions/4922305/how-can-i-change-font-size-in-eclipse-for-java-text-editors

to change color with a theme please check this http://www.eclipsecolorthemes.org/?view=theme&id=93

**Comment by MarcoLopezPE** [comment]
Ahh, understood!
Thanks for the explanation, the rest if it worked.
Best regards
